export const ADMIN_SIGNIN_REQ = "ADMIN_SIGNIN_REQ"
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS"
export const ADMIN_SIGNIN_FAIL = "ADMIN_SIGNIN_FAIL"

export const ADMIN_SIGNUP_REQ = "ADMIN_SIGNUP_REQ"
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_FAIL = "ADMIN_SIGNUP_FAIL"

export const ADMIN_LOGOUT_REQ = "ADMIN_LOGOUT_REQ"
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS"
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL"